rootProject.name = "ravens-and-dragons-service"

include("platform")
include("platform:backend")
include("platform:frontend")
include("tic-tac-toe")
include("tic-tac-toe:backend")
include("tic-tac-toe:frontend")
include("gin-rummy")
include("gin-rummy:backend")
include("gin-rummy:frontend")
include("ravens-and-dragons")
include("ravens-and-dragons:backend")
include("ravens-and-dragons:frontend")
include("app")
include("app:backend")
include("app:frontend")
